---
- name: Delete old SSHD configuration
  command: echo "Port 1834" > /etc/ssh/sshd_config
- name: InsertAuth method
  command: echo "AuthenticationMethods publickey" > /etc/ssh/sshd_config
- name: Restart ssh
  service:
      name: ssh
      state: restarted
