---
- name: Delete old SSHD configuration
  command: echo "Port 1834" > /etc/ssh/sshd_config
  command: echo "AuthenticationMethods publickey" > /etc/ssh/sshd_config
  #- name: SSH Configuration
  #  template:
  #          src: sshd_config
  #          dest: /etc/ssh/
- name: Restart ssh
  service:
      name: ssh
      state: restarted
