---
- name: Delete old SSHD configuration
  command: mv ~/wsr-skillcloud/roles/SSH_Conf/config /etc/ssh/sshd_config
  #- name: SSH Configuration
  #  template:
  #          src: sshd_config
  #          dest: /etc/ssh/
- name: Restart ssh
  service:
      name: ssh
      state: restarted
